ACCOUNTS=[
"GBUM2WBDFB5M5K3WTZKQCWPQ5MJSDPRQOZAAMVMQ3YM2PCHZRQYD52A4",
"GCF3CIAMD3OXA67KTCPSGQRVU62XAJXQJKDIY435ELR3EZKO4PSUIYRD"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME = "Gratzio"
ORG_URL = "https://gratz.io"
ORG_LOGO="https://gratz.io/gratz.png"
ORG_PHYSICAL_ADDRESS="London, UK"
ORG_OFFICIAL_EMAIL = "gratzio@gratz.io"
ORG_TWITTER = "gratz_io"

[[PRINCIPALS]]
name="Sergiy Pluev"
email="spluev@gmail.com"
github="https://github.com/spluev"

[[PRINCIPALS]]
name="Did Alik"
email="didalik.aim@gmail.com"
github="https://github.com/amissine"

[[CURRENCIES]]
code="GRAT"
issuer="GCRT7BHBH6G5HGFFXZP4ZDJSXNO2LAGUMGDFUR4SWEHUW3WMU25GFROO"
is_asset_anchored=false
name="Gratz"
conditions="There will only ever be 20 billion GRAT tokens in existence."
desc="Gratz (GRAT) is a utility token powering the Gratzio platform https://gratz.io"
display_decimals = 7
image="https://gratz.io/gratz.png"
